### ISSUE TITLE
Can't remove empty spaces

### ISSUE THREAD

**Issue by NarZook** [Toofifty/rl-goal-tracker#10] opened 2022-07-07 12:06 UTC
![image](https://user-images.githubusercontent.com/45111338/177769110-a42eb67b-3703-478d-8d20-5d7c68d377bc.png)

Any idea how to remove these empty "0/0" spaces? I just want there to be "My Goals".

**Comment by T1biriy** [comment] 2022-07-27 10:14
Got the same problem, somewhat annoying

**Comment by cecilia-sanare** [comment] 2024-01-03 18:52
Closing as a duplicate of #3, feel free to reopen this if you still encounter this issue after https://github.com/runelite/plugin-hub/pull/5339 is approved and deployed.

**Closed by cecilia-sanare** 2024-01-03 18:52 UTC
Labels: bug
